name: cppcheck-full

on:
  pull_request:

jobs:
  cppcheck-full:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake git libpcre3-dev

      # cppcheck from apt does not yet support --check-level args, and thus install from source
      - name: Install Cppcheck from source
        run: |
          mkdir /tmp/cppcheck
          git clone https://github.com/danmar/cppcheck.git /tmp/cppcheck
          cd /tmp/cppcheck
          git checkout 2.14.1
          mkdir build
          cd build
          cmake ..
          make -j $(nproc)
          sudo make install

      - name: Get all C++ files
        id: all-files
        run: |
          find . -type f \( -name "*.cpp" -o -name "*.hpp" \) > all_files.txt
          cat all_files.txt

      - name: Run Cppcheck on all files
        id: cppcheck
        continue-on-error: true
        run: |
          files=$(cat all_files.txt)
          if [ -n "$files" ]; then
            echo "Running Cppcheck on all files: $files"
            cppcheck --enable=all --inconclusive --check-level=exhaustive --error-exitcode=1 --suppressions-list=.cppcheck_suppressions $files 2> cppcheck-report.txt || true
          else
            echo "No C++ files found."
            touch cppcheck-report.txt
          fi
        shell: bash

      - name: Show cppcheck-report result
        run: |
          echo "Cppcheck report content:"
          cat cppcheck-report.txt

      - name: Upload Cppcheck report
        uses: actions/upload-artifact@v2
        with:
          name: cppcheck-report
          path: cppcheck-report.txt

      - name: Check for Cppcheck errors
        id: check-cppcheck-errors
        run: |
          if grep -q 'error' cppcheck-report.txt; then
            echo "Cppcheck found errors."
            echo "cppcheck-errors=true" >> $GITHUB_ENV
          else
            echo "No errors found by Cppcheck."
            echo "cppcheck-errors=false" >> $GITHUB_ENV
          fi

      - name: Fail the job if Cppcheck found errors
        if: env.cppcheck-errors == 'true'
        run: |
          echo "Cppcheck found errors, failing the job."
          exit 1
